package com.hexacta.booster.codegeneration.persistence.layer;

/**
 * This class maintains the state of the string generated by
 * PersistableClassGenerator. This string represents the text the
 * PersistableClass.
 */

public class PersistableClass {

    private Class<?> modelClass;

    private String text;

    private String className;

    public PersistableClass(final Class<?> modelClass, final String className) {
        text = "";
        this.modelClass = modelClass;
        this.className = className;
    }

    public String getText() {
        return text;
    }

    public void append(final String atext) {
        text = text + atext;
    }

    public Class<?> getModelClass() {
        return modelClass;
    }

    public String getClassName() {
        return className;
    }

}
