package com.hexacta.booster.codegeneration.persistence.layer;

/**
 * This class maintains the state of the string generated by
 * MappingAdministratorGenerator. This string represents the text of the test
 * for the MappingAdministrator.
 */

public class MappingAdministrator {

    private String text;

    public MappingAdministrator() {

        text = "";
    }

    public String getText() {
        return text;
    }

    public void append(final String atext) {
        text = text + atext;
    }

}
