package com.hexacta.booster.codegeneration.persistence.layer;

/**
 * This class maintains the state of the string generated by
 * PersistenceLayerGenerator. This string represents the text of the
 * PersistenceLayer.
 */

public class PersistenceSession {

    private String text;

    public PersistenceSession() {
        text = "";
    }

    public String getText() {
        return text;
    }

    public void append(final String aText) {
        text = text + aText;
    }

}
