package com.hexacta.booster.codegeneration.persistence.layer;

/**
 * This class maintains the state of the string generated by
 * PersistenceLayerTestGenerator. This string represents the text of the test
 * for the PersistenceLayer.
 */
public class PersistenceSessionTest {

    private String text;

    public PersistenceSessionTest() {
        text = "";
    }

    public String getText() {
        return text;
    }

    public void append(final String aText) {
        text = text + aText;
    }

}
