package com.hexacta.booster.codegeneration.persistence.layer.hibernate;

/**
 * 
 */
public class SearchCriteria {

    /**
     * This class keeps the text generated by SearchCriteriaGenerator.
     */

    private String text;

    public SearchCriteria() {
        text = "";
    }

    public void append(final String aText) {
        text = text + aText;
    }

    public String getText() {
        return text;
    }
}
